permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "吴夏 WU Chat"
email: "xia.wu.france@hotmail.com"
description: "移动项目经理MPM, 新时代IP的助产士"
github_username:  "WUChat"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "WUChat"



url: "http://wuchat.github.io"
imgrepo: "http://blog.rainyalley.com/static/img"
imgrepo2: "http://wuchat.github.io/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

